export const DiningConfig = {
  id: 'dining',
  title: 'Dining',
  order: 3,
  trackingKey: 'dinning_category_click',
  iconKey: 'dining',
  image:
    'https://images.unsplash.com/photo-1666635017292-0ff081752858?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  path: '/dinning',

  desktop: {
    columns: [
      {
        title: 'Dining Tables',
        order: 1,
        groups: [
          {
            title: 'By Seating Capacity',
            order: 1,
            items: [
              {
                id: 'dinning-table-2-seater',
                title: '2 Seater Tables',
                path: '/dinning-tables/2-seater',
                image: 'https://cdn.pixabay.com/photo/2020/08/27/07/31/restaurant-5521372_1280.jpg',
                order: 1,
                trackingKey: 'dinning_table_2_seater_click',
                filter: { category: 'dinning', subCategory: 'Dining Tables', seatingCapacity: '2 Seater' },
              },
              {
                id: 'dinning-table-4-seater',
                title: '4 Seater Tables',
                path: '/dinning-tables/4-seater',
                image: 'https://cdn.pixabay.com/photo/2017/04/27/08/18/champagne-2264811_1280.jpg',
                order: 2,
                trackingKey: 'dinning_table_4_seater_click',
                filter: { category: 'dinning', subCategory: 'Dining Tables', seatingCapacity: '4 Seater' },
              },
              {
                id: 'dinning-table-6-seater',
                title: '6 Seater Tables',
                path: '/dinning-tables/6-seater',
                image: 'https://cdn.pixabay.com/photo/2020/04/18/08/06/furniture-5058151_1280.jpg',
                order: 3,
                trackingKey: 'dinning_table_6_seater_click',
                filter: { category: 'dinning', subCategory: 'Dining Tables', seatingCapacity: '6 Seater' },
              },
            ],
          },
          {
            title: 'By Material',
            order: 2,
            items: [
              {
                id: 'wooden-dinning-tables',
                title: 'Wooden Tables',
                path: '/dinning-tables/wooden',
                image: 'https://cdn.pixabay.com/photo/2020/04/18/08/06/furniture-5058151_1280.jpg',
                order: 1,
                trackingKey: 'dinning_table_wooden_click',
                filter: { category: 'dinning', subCategory: 'Dining Tables', material: 'Wood' },
              },
              {
                id: 'glass-dinning-tables',
                title: 'Glass Tables',
                path: '/dinning-tables/glass',
                image: 'https://cdn.pixabay.com/photo/2015/10/26/00/00/dining-room-1006525_1280.jpg',
                order: 2,
                trackingKey: 'dinning_table_glass_click',
                filter: { category: 'dinning', subCategory: 'Dining Tables', material: 'Glass' },
              },
              {
                id: 'marble-dinning-tables',
                title: 'Marble Tables',
                path: '/dinning-tables/marble',
                image: 'https://cdn.pixabay.com/photo/2016/11/21/15/19/chairs-1845932_1280.jpg',
                order: 3,
                trackingKey: 'dinning_table_marble_click',
                filter: { category: 'dinning', subCategory: 'Dining Tables', material: 'Marble' },
              },
            ],
          },
        ],
      },

      {
        title: 'Dining Sets',
        order: 2,
        items: [
          {
            id: 'all-dinning-sets',
            title: 'All Dining Sets',
            path: '/dinning-table-sets',
            image: 'https://cdn.pixabay.com/photo/2022/09/12/08/17/dinning-room-7448859_1280.jpg',
            order: 1,
            trackingKey: 'dinning_set_all_click',
            filter: { category: 'dinning', subCategory: 'Dining Table Sets' },
          },
          {
            id: 'dinning-set-4-seater',
            title: '4 Seater Sets',
            path: '/dinning-table-sets/4-seater',
            image: 'https://cdn.pixabay.com/photo/2017/04/27/08/18/champagne-2264811_1280.jpg',
            order: 2,
            trackingKey: 'dinning_set_4_seater_click',
            filter: { category: 'dinning', subCategory: 'Dining Table Sets', seatingCapacity: '4 Seater' },
          },
          {
            id: 'dinning-set-6-seater',
            title: '6 Seater Sets',
            path: '/dinning-table-sets/6-seater',
            image: 'https://cdn.pixabay.com/photo/2018/01/26/08/15/dining-room-3108037_1280.jpg',
            order: 3,
            trackingKey: 'dinning_set_6_seater_click',
            filter: { category: 'dinning', subCategory: 'Dining Table Sets', seatingCapacity: '6 Seater' },
          },
        ],
      },

      {
        title: 'Seating & Extras',
        order: 3,
        items: [
          {
            id: 'dinning-chairs',
            title: 'Dining Chairs',
            path: '/dinning-chairs',
            image: 'https://cdn.pixabay.com/photo/2017/03/20/19/57/chairs-2160184_1280.jpg',
            order: 1,
            trackingKey: 'dinning_chair_all_click',
            filter: { category: 'dinning', subCategory: 'Chairs' },
          },
          {
            id: 'dinning-benches',
            title: 'Benches',
            path: '/dinning-benches',
            image: 'https://cdn.pixabay.com/photo/2017/08/03/14/32/bank-2576595_1280.png',
            order: 2,
            trackingKey: 'dinning_bench_click',
            filter: { category: 'dinning', subCategory: 'Benches' },
          },
          {
            id: 'dinning-stools',
            title: 'Stools',
            path: '/dinning-stools',
            image: 'https://cdn.pixabay.com/photo/2015/03/30/12/49/stools-698681_1280.jpg',
            order: 3,
            trackingKey: 'dinning_stool_click',
            filter: { category: 'dinning', subCategory: 'Stools' },
          },
        ],
      },
    ],

    promo: {
      image: 'https://cdn.pixabay.com/photo/2022/09/12/08/17/dinning-room-7448859_1280.jpg',
      path: '/dinning-tables',
      trackingKey: 'dinning_promo_click',
    },
  },

  mobile: {
    topGrid: [
      {
        id: 'wooden-dinning-tables',
        title: 'Wooden Tables',
        image: 'https://cdn.pixabay.com/photo/2020/04/18/08/06/furniture-5058151_1280.jpg',
        path: '/dinning-tables/wooden',
        order: 1,
        trackingKey: 'mobile_dinning_table_wooden_click',
        filter: { category: 'dinning', subCategory: 'Dining Tables', material: 'Wood' },
      },
      {
        id: 'dinning-table-4-seater',
        title: '4 Seater Tables',
        image: 'https://cdn.pixabay.com/photo/2017/04/27/08/18/champagne-2264811_1280.jpg',
        path: '/dinning-tables/4-seater',
        order: 2,
        trackingKey: 'mobile_dinning_table_4_seater_click',
        filter: { category: 'dinning', subCategory: 'Dining Tables', seatingCapacity: '4 Seater' },
      },
      {
        id: 'dinning-set-6-seater',
        title: '6 Seater Sets',
        image: 'https://cdn.pixabay.com/photo/2018/01/26/08/15/dining-room-3108037_1280.jpg',
        path: '/dinning-table-sets/6-seater',
        order: 3,
        trackingKey: 'mobile_dinning_set_6_seater_click',
        filter: { category: 'dinning', subCategory: 'Dining Table Sets', seatingCapacity: '6 Seater' },
      },
      {
        id: 'dinning-chairs',
        title: 'Chairs',
        image: 'https://cdn.pixabay.com/photo/2017/03/20/19/57/chairs-2160184_1280.jpg',
        path: '/dinning-chairs',
        order: 4,
        trackingKey: 'mobile_dinning_chair_click',
        filter: { category: 'dinning', subCategory: 'Chairs' },
      },
      {
        id: 'dinning-benches',
        title: 'Benches',
        image: 'https://cdn.pixabay.com/photo/2017/08/03/14/32/bank-2576595_1280.png',
        path: '/dinning-benches',
        order: 5,
        trackingKey: 'mobile_dinning_bench_click',
        filter: { category: 'dinning', subCategory: 'Benches' },
      },
      {
        id: 'dinning-stools',
        title: 'Stools',
        image: 'https://cdn.pixabay.com/photo/2015/03/30/12/49/stools-698681_1280.jpg',
        path: '/dinning-stools',
        order: 6,
        trackingKey: 'mobile_dinning_stool_click',
        filter: { category: 'dinning', subCategory: 'Stools' },
      },
    ],
  },
}
