export const LivingConfig = {
  id: 'living',
  title: 'Living',
  order: 5,
  trackingKey: 'living_category_click',
  iconKey: 'living',
  image:
    'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  path: '/living',

  desktop: {
    columns: [
      {
        title: 'Seating & Sofas',
        order: 1,
        groups: [
          {
            title: 'Sofa Sets',
            order: 1,
            items: [
              {
                id: 'all-sofa-sets',
                title: 'All Sofa Sets',
                path: '/sofas',
                image: 'https://cdn.pixabay.com/photo/2017/01/07/17/48/interior-1961070_1280.jpg',
                order: 1,
                trackingKey: 'sofa_set_all_click',
                filter: { category: 'living', subCategory: 'Sofa Sets' },
              },
              {
                id: '2-seater-sofas',
                title: '2 Seater Sofas',
                path: '/sofas/2-seater',
                image: 'https://cdn.pixabay.com/photo/2015/07/08/23/04/sofa-837019_1280.jpg',
                order: 2,
                trackingKey: 'sofa_2_seater_click',
                filter: { category: 'living', subCategory: 'Sofa Sets', seatingCapacity: '2 Seater' },
              },
              {
                id: '3-seater-sofas',
                title: '3 Seater Sofas',
                path: '/sofas/3-seater',
                image: 'https://cdn.pixabay.com/photo/2017/08/19/02/58/sofa-2657172_1280.png',
                order: 3,
                trackingKey: 'sofa_3_seater_click',
                filter: { category: 'living', subCategory: 'Sofa Sets', seatingCapacity: '3 Seater' },
              },
              {
                id: 'l-shaped-sofas',
                title: 'L-Shaped Sofas',
                path: '/sofas/l-shaped',
                image: 'https://cdn.pixabay.com/photo/2020/02/20/06/24/sofa-4864034_1280.jpg',
                order: 4,
                trackingKey: 'sofa_l_shaped_click',
                filter: { category: 'living', subCategory: 'Sofa Sets', style: 'L-Shaped' },
              },
            ],
          },
          {
            title: 'Chairs & Recliners',
            order: 2,
            items: [
              {
                id: 'lounge-chairs',
                title: 'Lounge Chairs',
                path: '/chairs/lounge',
                image: 'https://cdn.pixabay.com/photo/2017/03/18/19/19/chair-2154732_1280.jpg',
                order: 1,
                trackingKey: 'lounge_chair_click',
                filter: { category: 'living', subCategory: 'Lounge Chairs' },
              },
              {
                id: 'recliners',
                title: 'Recliners',
                path: '/chairs/recliners',
                image: 'https://cdn.pixabay.com/photo/2023/11/15/13/36/chair-8390091_1280.jpg',
                order: 2,
                trackingKey: 'recliner_click',
                filter: { category: 'living', subCategory: 'Recliners' },
              },
              {
                id: 'ottomans-pouffes',
                title: 'Round Ottomans & Footstools',
                path: '/chairs/ottomans',
                image: 'https://cdn.pixabay.com/photo/2024/03/26/18/56/interior-design-8657614_1280.png',
                order: 3,
                trackingKey: 'ottoman_pouffe_click',
                filter: { category: 'living', subCategory: 'Ottomans & Pouffes' },
              },
            ],
          },
        ],
      },

      {
        title: 'Tables & Storage',
        order: 2,
        groups: [
          {
            title: 'Tables',
            order: 1,
            items: [
              {
                id: 'coffee-tables',
                title: 'Coffee Tables',
                path: '/tables/coffee',
                image: 'https://cdn.pixabay.com/photo/2023/08/30/17/29/ai-generated-8223835_1280.jpg',
                order: 1,
                trackingKey: 'coffee_table_click',
                filter: { category: 'living', subCategory: 'Coffee Tables' },
              },
              {
                id: 'nest-of-tables',
                title: 'Nest of Tables',
                path: '/tables/nest',
                image: 'https://woodencrest.com/cdn/shop/files/11.webp?v=1733148987',
                order: 2,
                trackingKey: 'nest_table_click',
                filter: { category: 'living', subCategory: 'Nest of Tables' },
              },
              {
                id: 'side-end-tables',
                title: 'Side & End Tables',
                path: '/tables/side-end',
                image:
                  'https://woodencrest.com/cdn/shop/files/394_5dff99bc-a712-425f-b589-66dc72dff983.webp?v=1733412876',
                order: 3,
                trackingKey: 'side_end_table_click',
                filter: { category: 'living', subCategory: 'Side & End Tables' },
              },
            ],
          },
          {
            title: 'TV Units & Cabinets',
            order: 2,
            items: [
              {
                id: 'tv-units',
                title: 'TV Units & Stands',
                path: '/tv-units',
                image: 'https://cdn.pixabay.com/photo/2014/08/11/21/39/wall-416060_1280.jpg',
                order: 1,
                trackingKey: 'tv_unit_click',
                filter: { category: 'living', subCategory: 'TV Units' },
              },
              {
                id: 'cabinets-sideboards',
                title: 'Cabinets & Sideboards',
                path: '/storage/cabinets',
                image: 'https://cdn.pixabay.com/photo/2021/02/25/04/44/furniture-6048139_1280.jpg',
                order: 2,
                trackingKey: 'cabinet_sideboard_click',
                filter: { category: 'living', subCategory: 'Cabinets & Sideboards' },
              },
            ],
          },
        ],
      },

      {
        title: 'Display & Shelving',
        order: 3,
        items: [
          {
            id: 'bookshelves',
            title: 'Bookshelves',
            path: '/storage/bookshelves',
            image: 'https://cdn.pixabay.com/photo/2020/08/11/18/11/woman-5480770_1280.jpg',
            order: 1,
            trackingKey: 'bookshelf_click',
            filter: { category: 'living', subCategory: 'Bookshelves' },
          },
          {
            id: 'wall-shelves',
            title: 'Wall Shelves',
            path: '/storage/wall-shelves',
            image: 'https://cdn.pixabay.com/photo/2015/10/20/18/57/furniture-998265_1280.jpg',
            order: 2,
            trackingKey: 'wall_shelf_click',
            filter: { category: 'living', subCategory: 'Wall Shelves' },
          },
          {
            id: 'benches',
            title: 'Benches & Accent Seats',
            path: '/storage/benches',
            image: 'https://cdn.pixabay.com/photo/2017/08/03/12/51/bench-2576083_1280.jpg',
            order: 3,
            trackingKey: 'bench_click',
            filter: { category: 'living', subCategory: 'Benches & Accent Seats' },
          },
        ],
      },
    ],

    promo: {
      image: 'https://cdn.pixabay.com/photo/2019/05/03/14/23/interior-4175975_1280.jpg',
      path: '/sofas',
      trackingKey: 'living_promo_click',
    },
  },

  mobile: {
    topGrid: [
      {
        id: '3-seater-sofas',
        title: '3 Seater Sofas',
        image: 'https://cdn.pixabay.com/photo/2022/01/08/08/07/house-6923506_1280.jpg',
        path: '/sofas/3-seater',
        order: 1,
        trackingKey: 'mobile_sofa_3_seater_click',
        filter: { category: 'living', subCategory: 'Sofa Sets', seatingCapacity: '3 Seater' },
      },
      {
        id: 'lounge-chairs',
        title: 'Lounge Chairs',
        image: 'https://cdn.pixabay.com/photo/2017/03/19/18/52/armchair-2157356_1280.jpg',
        path: '/chairs/lounge',
        order: 2,
        trackingKey: 'mobile_lounge_chair_click',
        filter: { category: 'living', subCategory: 'Lounge Chairs' },
      },
      {
        id: 'coffee-tables',
        title: 'Coffee Tables',
        image: 'https://cdn.pixabay.com/photo/2023/08/30/17/29/ai-generated-8223835_1280.jpg',
        path: '/tables/coffee',
        order: 3,
        trackingKey: 'mobile_coffee_table_click',
        filter: { category: 'living', subCategory: 'Coffee Tables' },
      },
      {
        id: 'tv-units',
        title: 'TV Units',
        image: 'https://cdn.pixabay.com/photo/2014/08/11/21/39/wall-416060_1280.jpg',
        path: '/tv-units',
        order: 4,
        trackingKey: 'mobile_tv_unit_click',
        filter: { category: 'living', subCategory: 'TV Units' },
      },
      {
        id: 'bookshelves',
        title: 'Bookshelves',
        image: 'https://cdn.pixabay.com/photo/2020/08/11/18/11/woman-5480770_1280.jpg',
        path: '/storage/bookshelves',
        order: 5,
        trackingKey: 'mobile_bookshelf_click',
        filter: { category: 'living', subCategory: 'Bookshelves' },
      },
      {
        id: 'benches',
        title: 'Benches',
        image: 'https://cdn.pixabay.com/photo/2017/08/03/12/51/bench-2576083_1280.jpg',
        path: '/storage/benches',
        order: 6,
        trackingKey: 'mobile_bench_click',
        filter: { category: 'living', subCategory: 'Benches & Accent Seats' },
      },
    ],
  },
}
