export const SofaConfig = {
  id: 'sofas',
  title: 'Sofas',
  order: 1,
  trackingKey: 'sofa_category_click',
  iconKey: 'sofas',
  image:
    'https://plus.unsplash.com/premium_photo-1683140554145-c7fb8c93cb36?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  path: '/sofas',

  desktop: {
    columns: [
      {
        title: 'Sofas',
        order: 1,
        items: [
          {
            id: 'all-sofas',
            title: 'All Sofas',
            path: '/sofas',
            image: 'https://cdn.pixabay.com/photo/2017/08/02/01/01/living-room-2569325_1280.jpg',
            order: 1,
            trackingKey: 'sofa_all_click',
            filter: { category: 'sofa' },
          },
          {
            id: 'fabric-sofas',
            title: 'Fabric Sofas',
            path: '/sofas/fabric',
            image: 'https://cdn.pixabay.com/photo/2024/09/17/11/19/real-estate-9053405_1280.jpg',
            order: 2,
            trackingKey: 'sofa_fabric_click',
            filter: { category: 'sofa', subCategory: 'Fabric Sofas' },
          },
          {
            id: 'wooden-sofas',
            title: 'Wooden Sofas',
            path: '/sofas/wooden',
            image: 'https://cdn.pixabay.com/photo/2023/12/31/15/42/living-room-8480223_1280.jpg',
            order: 3,
            trackingKey: 'sofa_wooden_click',
            filter: { category: 'sofa', subCategory: 'Wooden Sofas', material: 'Wood' },
          },
          {
            id: 'three-seater-sofas',
            title: '3 Seater Sofas',
            path: '/sofas/3-seater',
            image: 'https://cdn.pixabay.com/photo/2022/01/08/08/07/house-6923506_1280.jpg',
            order: 4,
            trackingKey: 'sofa_3_seater_click',
            filter: { category: 'sofa', seatingCapacity: '3 Seater' },
          },
          {
            id: 'l-shaped-sofas',
            title: 'L-Shaped Sofas',
            path: '/sofas/l-shaped',
            image: 'https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939_1280.jpg',
            order: 5,
            trackingKey: 'sofa_l_shaped_click',
            filter: { category: 'sofa', style: 'L-Shaped' },
          },
        ],
      },

      {
        order: 2,
        groups: [
          {
            title: 'Sofa Cum Beds',
            order: 1,
            items: [
              {
                id: 'all-sofa-cum-beds',
                title: 'All Sofa Cum Beds',
                path: '/sofa-cum-beds',
                image: 'https://cdn.pixabay.com/photo/2023/05/19/14/32/bedroom-8004697_1280.jpg',
                order: 1,
                trackingKey: 'sofa_cum_bed_all_click',
                filter: { category: 'sofa', subCategory: 'Sofa Cum Beds' },
              },
              {
                id: 'wooden-sofa-cum-beds',
                title: 'Wooden Sofa Cum Beds',
                path: '/sofa-cum-beds/wooden',
                image: 'https://cdn.pixabay.com/photo/2021/12/18/06/00/room-6878004_1280.jpg',
                order: 2,
                trackingKey: 'sofa_cum_bed_wooden_click',
                filter: { category: 'sofa', subCategory: 'Sofa Cum Beds', material: 'Wood' },
              },
            ],
          },
          {
            title: 'Recliners',
            order: 2,
            items: [
              {
                id: 'all-recliners',
                title: 'All Recliners',
                path: '/recliners',
                image: 'https://cdn.pixabay.com/photo/2015/12/05/23/45/sofa-1078931_1280.jpg',
                order: 1,
                trackingKey: 'recliner_all_click',
                filter: { category: 'sofa', subCategory: 'Recliners' },
              },
              {
                id: 'single-seater-recliners',
                title: '1 Seater Recliners',
                path: '/recliners/1-seater',
                image: 'https://cdn.pixabay.com/photo/2017/03/19/01/43/living-room-2155376_1280.jpg',
                order: 2,
                trackingKey: 'recliner_1_seater_click',
                filter: { category: 'sofa', subCategory: 'Recliners', seatingCapacity: '1 Seater' },
              },
            ],
          },
        ],
      },

      {
        title: 'Seating',
        order: 3,
        items: [
          {
            id: 'lounge-chairs',
            title: 'Lounge Chairs',
            path: '/chairs/lounge',
            image: 'https://cdn.pixabay.com/photo/2017/03/19/18/52/armchair-2157356_1280.jpg',
            order: 1,
            trackingKey: 'lounge_chair_click',
            filter: { category: 'seating', subCategory: 'Lounge Chairs' },
          },
          {
            id: 'accent-chairs',
            title: 'Accent Chairs',
            path: '/chairs/accent',
            image: 'https://cdn.pixabay.com/photo/2018/04/05/16/38/chair-3293322_1280.jpg',
            order: 2,
            trackingKey: 'accent_chair_click',
            filter: { category: 'seating', subCategory: 'Accent Chairs' },
          },
        ],
      },
    ],

    promo: {
      image: 'https://cdn.pixabay.com/photo/2016/10/11/03/54/home-1730489_1280.jpg',
      path: '/sofas',
      trackingKey: 'sofa_promo_click',
    },
  },

  mobile: {
    topGrid: [
      {
        id: 'fabric-sofas',
        title: 'Fabric Sofas',
        image: 'https://cdn.pixabay.com/photo/2024/09/17/11/19/real-estate-9053405_1280.jpg',
        path: '/sofas/fabric',
        order: 1,
        trackingKey: 'mobile_sofa_fabric_click',
        filter: { category: 'sofa', subCategory: 'Fabric Sofas' },
      },
      {
        id: 'wooden-sofas',
        title: 'Wooden Sofas',
        image: 'https://cdn.pixabay.com/photo/2023/12/31/15/42/living-room-8480223_1280.jpg',
        path: '/sofas/wooden',
        order: 2,
        trackingKey: 'mobile_sofa_wooden_click',
        filter: { category: 'sofa', subCategory: 'Wooden Sofas', material: 'Wood' },
      },
      {
        id: 'three-seater-sofas',
        title: '3 Seater',
        image: 'https://cdn.pixabay.com/photo/2022/01/08/08/07/house-6923506_1280.jpg',
        path: '/sofas/3-seater',
        order: 3,
        trackingKey: 'mobile_sofa_3_seater_click',
        filter: { category: 'sofa', seatingCapacity: '3 Seater' },
      },
      {
        id: 'recliners',
        title: 'Recliners',
        image: 'https://cdn.pixabay.com/photo/2020/04/17/12/27/sofa-5055005_1280.jpg',
        path: '/recliners',
        order: 4,
        trackingKey: 'mobile_recliner_click',
        filter: { category: 'sofa', subCategory: 'Recliners' },
      },
      {
        id: 'sofa-cum-beds',
        title: 'Sofa Cum Bed',
        image: 'https://cdn.pixabay.com/photo/2023/05/19/14/32/bedroom-8004697_1280.jpg',
        path: '/sofa-cum-beds',
        order: 5,
        trackingKey: 'mobile_sofa_cum_bed_click',
        filter: { category: 'sofa', subCategory: 'Sofa Cum Beds' },
      },
      {
        id: 'l-shaped-sofas',
        title: 'L-Shaped',
        image: 'https://cdn.pixabay.com/photo/2017/09/09/18/25/living-room-2732939_1280.jpg',
        path: '/sofas/l-shaped',
        order: 6,
        trackingKey: 'mobile_sofa_l_shaped_click',
        filter: { category: 'sofa', style: 'L-Shaped' },
      },
    ],
  },
}
